/*******************************************************************************
 * Copyright (c) 2012 SAP AG and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     SAP AG - initial API and implementation
 *******************************************************************************/
package org.eclipse.servicesregistry.proxy;

/**
 * Service implementation of {ServicesRegistrySiService} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "ServicesRegistrySiService", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", wsdlLocation = "wsdl/servicesregistry.wsdl")
public class ServicesRegistrySiService extends javax.xml.ws.Service {

  private final static java.net.URL SERVICESREGISTRYSISERVICE_WSDL_LOCATION;
  static {
    java.net.URL url = null;
    try {
		java.net.URL tmpUrl = ServicesRegistrySiService.class.getClassLoader().getResource("wsdl/servicesregistry.wsdl");
		url = new java.net.URL(tmpUrl.getProtocol(), tmpUrl.getHost(), tmpUrl.getPort(), tmpUrl.getFile());
    } catch (java.net.MalformedURLException e) {
      e.printStackTrace();
    }
    SERVICESREGISTRYSISERVICE_WSDL_LOCATION = url;
  }
  /**
   * Default service constructor.
   */
  public ServicesRegistrySiService() throws java.net.MalformedURLException {
    super(SERVICESREGISTRYSISERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://sap.com/esi/uddi/sr/api/ws/", "ServicesRegistrySiService"));
  }
  public ServicesRegistrySiService(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [ServicesRegistrySiPort].
   */
  @javax.xml.ws.WebEndpoint(name = "ServicesRegistrySiPort")
  public org.eclipse.servicesregistry.proxy.ServicesRegistrySi getServicesRegistrySiPort() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://sap.com/esi/uddi/sr/api/ws/","ServicesRegistrySiPort");
    return (org.eclipse.servicesregistry.proxy.ServicesRegistrySi) super.getPort(portName,org.eclipse.servicesregistry.proxy.ServicesRegistrySi.class);
  }
}
