/*******************************************************************************
 * Copyright (c) 2012 SAP AG and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     SAP AG - initial API and implementation
 *******************************************************************************/
package org.eclipse.servicesregistry.proxy;


/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "ServicesRegistrySi", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.WRAPPED, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface ServicesRegistrySi {

  /**
   * Java representation of web method [getVersionInfo].
   */
  @javax.jws.WebMethod(operationName = "getVersionInfo")
  @javax.xml.ws.RequestWrapper(localName = "getVersionInfo", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.GetVersionInfo")
  @javax.xml.ws.ResponseWrapper(localName = "getVersionInfoResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.GetVersionInfoResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public java.lang.String getVersionInfo() throws org.eclipse.servicesregistry.proxy.types.GetVersionInfoFault;

  /**
   * Java representation of web method [publishWSDL].
   */
  @javax.jws.WebMethod(operationName = "publishWSDL")
  @javax.xml.ws.RequestWrapper(localName = "publishWSDL", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.PublishWSDL")
  @javax.xml.ws.ResponseWrapper(localName = "publishWSDLResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.PublishWSDLResponse")
  public void publishWSDL(@javax.jws.WebParam(name = "wsdlURL", targetNamespace = "") java.lang.String wsdlURL) throws org.eclipse.servicesregistry.proxy.types.PublishWSDLFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySipublishWSDLFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySipublishWSDLFault1,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySipublishWSDLFault12;

  /**
   * Java representation of web method [getPhysicalSystems].
   */
  @javax.jws.WebMethod(operationName = "getPhysicalSystems")
  @javax.xml.ws.RequestWrapper(localName = "getPhysicalSystems", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.GetPhysicalSystems")
  @javax.xml.ws.ResponseWrapper(localName = "getPhysicalSystemsResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.GetPhysicalSystemsResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public java.util.List<org.eclipse.servicesregistry.proxy.types.PhysicalSystem> getPhysicalSystems(@javax.jws.WebParam(name = "physicalSystemKeys", targetNamespace = "") java.util.List<org.eclipse.servicesregistry.proxy.types.PhysicalSystemKey> physicalSystemKeys) throws org.eclipse.servicesregistry.proxy.types.GetPhysicalSystemsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySigetPhysicalSystemsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySigetPhysicalSystemsFault1,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySigetPhysicalSystemsFault12;

  /**
   * Java representation of web method [getServiceDefinitions].
   */
  @javax.jws.WebMethod(operationName = "getServiceDefinitions")
  @javax.xml.ws.RequestWrapper(localName = "getServiceDefinitions", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.GetServiceDefinitions")
  @javax.xml.ws.ResponseWrapper(localName = "getServiceDefinitionsResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.GetServiceDefinitionsResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public java.util.List<org.eclipse.servicesregistry.proxy.types.ServiceDefinition> getServiceDefinitions(@javax.jws.WebParam(name = "serviceDefinitionKeys", targetNamespace = "") java.util.List<org.eclipse.servicesregistry.proxy.types.ServiceDefinitionKey> serviceDefinitionKeys) throws org.eclipse.servicesregistry.proxy.types.GetServiceDefinitionsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySigetServiceDefinitionsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySigetServiceDefinitionsFault1,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySigetServiceDefinitionsFault12;

  /**
   * Java representation of web method [findService].
   */
  @javax.jws.WebMethod(operationName = "findService")
  @javax.xml.ws.RequestWrapper(localName = "findService", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.FindService")
  @javax.xml.ws.ResponseWrapper(localName = "findServiceResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.FindServiceResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public org.eclipse.servicesregistry.proxy.types.ServiceList findService(@javax.jws.WebParam(name = "serviceEndpointSearchAttributes", targetNamespace = "") org.eclipse.servicesregistry.proxy.types.ServiceEndpointSearchAttributes serviceEndpointSearchAttributes) throws org.eclipse.servicesregistry.proxy.types.FindServiceFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySifindServiceFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySifindServiceFault1,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySifindServiceFault12;

  /**
   * Java representation of web method [isKeywordSearchSupported].
   */
  @javax.jws.WebMethod(operationName = "isKeywordSearchSupported")
  @javax.xml.ws.RequestWrapper(localName = "isKeywordSearchSupported", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.IsKeywordSearchSupported")
  @javax.xml.ws.ResponseWrapper(localName = "isKeywordSearchSupportedResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.IsKeywordSearchSupportedResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public boolean isKeywordSearchSupported() throws org.eclipse.servicesregistry.proxy.types.IsKeywordSearchSupportedFault;

  /**
   * Java representation of web method [deleteClassificationSystems].
   */
  @javax.jws.WebMethod(operationName = "deleteClassificationSystems")
  @javax.xml.ws.RequestWrapper(localName = "deleteClassificationSystems", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.DeleteClassificationSystems")
  @javax.xml.ws.ResponseWrapper(localName = "deleteClassificationSystemsResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.DeleteClassificationSystemsResponse")
  public void deleteClassificationSystems(@javax.jws.WebParam(name = "classificationSystemKeys", targetNamespace = "") java.util.List<org.eclipse.servicesregistry.proxy.types.ClassificationSystemKey> classificationSystemKeys) throws org.eclipse.servicesregistry.proxy.types.DeleteClassificationSystemsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySideleteClassificationSystemsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySideleteClassificationSystemsFault1,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySideleteClassificationSystemsFault12;

  /**
   * Java representation of web method [deleteClassificationSystemValues].
   */
  @javax.jws.WebMethod(operationName = "deleteClassificationSystemValues")
  @javax.xml.ws.RequestWrapper(localName = "deleteClassificationSystemValues", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.DeleteClassificationSystemValues")
  @javax.xml.ws.ResponseWrapper(localName = "deleteClassificationSystemValuesResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.DeleteClassificationSystemValuesResponse")
  public void deleteClassificationSystemValues(@javax.jws.WebParam(name = "classificationSystemKeys", targetNamespace = "") java.util.List<org.eclipse.servicesregistry.proxy.types.ClassificationSystemKey> classificationSystemKeys) throws org.eclipse.servicesregistry.proxy.types.DeleteClassificationSystemValuesFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySideleteClassificationSystemValuesFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySideleteClassificationSystemValuesFault1,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySideleteClassificationSystemValuesFault12;

  /**
   * Java representation of web method [hidePhysicalSystems].
   */
  @javax.jws.WebMethod(operationName = "hidePhysicalSystems")
  @javax.xml.ws.RequestWrapper(localName = "hidePhysicalSystems", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.HidePhysicalSystems")
  @javax.xml.ws.ResponseWrapper(localName = "hidePhysicalSystemsResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.HidePhysicalSystemsResponse")
  public void hidePhysicalSystems(@javax.jws.WebParam(name = "physicalSystemKeys", targetNamespace = "") java.util.List<org.eclipse.servicesregistry.proxy.types.PhysicalSystemKey> physicalSystemKeys) throws org.eclipse.servicesregistry.proxy.types.HidePhysicalSystemsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySihidePhysicalSystemsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySihidePhysicalSystemsFault1,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySihidePhysicalSystemsFault12;

  /**
   * Java representation of web method [hideServiceDefinitions].
   */
  @javax.jws.WebMethod(operationName = "hideServiceDefinitions")
  @javax.xml.ws.RequestWrapper(localName = "hideServiceDefinitions", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.HideServiceDefinitions")
  @javax.xml.ws.ResponseWrapper(localName = "hideServiceDefinitionsResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.HideServiceDefinitionsResponse")
  public void hideServiceDefinitions(@javax.jws.WebParam(name = "serviceDefinitionKeys", targetNamespace = "") java.util.List<org.eclipse.servicesregistry.proxy.types.ServiceDefinitionKey> serviceDefinitionKeys) throws org.eclipse.servicesregistry.proxy.types.HideServiceDefinitionsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySihideServiceDefinitionsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySihideServiceDefinitionsFault1,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySihideServiceDefinitionsFault12;

  /**
   * Java representation of web method [findPhysicalSystems].
   */
  @javax.jws.WebMethod(operationName = "findPhysicalSystems")
  @javax.xml.ws.RequestWrapper(localName = "findPhysicalSystems", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.FindPhysicalSystems")
  @javax.xml.ws.ResponseWrapper(localName = "findPhysicalSystemsResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.FindPhysicalSystemsResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public org.eclipse.servicesregistry.proxy.types.PhysicalSystemList findPhysicalSystems(@javax.jws.WebParam(name = "physicalSystemSearchAttributes", targetNamespace = "") org.eclipse.servicesregistry.proxy.types.PhysicalSystemSearchAttributes physicalSystemSearchAttributes) throws org.eclipse.servicesregistry.proxy.types.FindPhysicalSystemsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySifindPhysicalSystemsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySifindPhysicalSystemsFault1,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySifindPhysicalSystemsFault12;

  /**
   * Java representation of web method [publishPhysicalSystems].
   */
  @javax.jws.WebMethod(operationName = "publishPhysicalSystems")
  @javax.xml.ws.RequestWrapper(localName = "publishPhysicalSystems", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.PublishPhysicalSystems")
  @javax.xml.ws.ResponseWrapper(localName = "publishPhysicalSystemsResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.PublishPhysicalSystemsResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public java.util.List<org.eclipse.servicesregistry.proxy.types.PhysicalSystemKey> publishPhysicalSystems(@javax.jws.WebParam(name = "physicalSystem", targetNamespace = "") java.util.List<org.eclipse.servicesregistry.proxy.types.PhysicalSystem> physicalSystem) throws org.eclipse.servicesregistry.proxy.types.PublishPhysicalSystemsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySipublishPhysicalSystemsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySipublishPhysicalSystemsFault1,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySipublishPhysicalSystemsFault12,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySipublishPhysicalSystemsFault123;

  /**
   * Java representation of web method [getClassificationSystems].
   */
  @javax.jws.WebMethod(operationName = "getClassificationSystems")
  @javax.xml.ws.RequestWrapper(localName = "getClassificationSystems", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.GetClassificationSystems")
  @javax.xml.ws.ResponseWrapper(localName = "getClassificationSystemsResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.GetClassificationSystemsResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public java.util.List<org.eclipse.servicesregistry.proxy.types.ClassificationSystem> getClassificationSystems(@javax.jws.WebParam(name = "classificationSystemKeys", targetNamespace = "") java.util.List<org.eclipse.servicesregistry.proxy.types.ClassificationSystemKey> classificationSystemKeys) throws org.eclipse.servicesregistry.proxy.types.GetClassificationSystemsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySigetClassificationSystemsFault;

  /**
   * Java representation of web method [publishServiceDefinitions].
   */
  @javax.jws.WebMethod(operationName = "publishServiceDefinitions")
  @javax.xml.ws.RequestWrapper(localName = "publishServiceDefinitions", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.PublishServiceDefinitions")
  @javax.xml.ws.ResponseWrapper(localName = "publishServiceDefinitionsResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.PublishServiceDefinitionsResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public java.util.List<org.eclipse.servicesregistry.proxy.types.ServiceDefinitionKey> publishServiceDefinitions(@javax.jws.WebParam(name = "definitions", targetNamespace = "") java.util.List<org.eclipse.servicesregistry.proxy.types.ServiceDefinition> definitions) throws org.eclipse.servicesregistry.proxy.types.PublishServiceDefinitionsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySipublishServiceDefinitionsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySipublishServiceDefinitionsFault1,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySipublishServiceDefinitionsFault12,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySipublishServiceDefinitionsFault123;

  /**
   * Java representation of web method [publishServices].
   */
  @javax.jws.WebMethod(operationName = "publishServices")
  @javax.xml.ws.RequestWrapper(localName = "publishServices", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.PublishServices")
  @javax.xml.ws.ResponseWrapper(localName = "publishServicesResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.PublishServicesResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public java.util.List<org.eclipse.servicesregistry.proxy.types.ServiceKey> publishServices(@javax.jws.WebParam(name = "service", targetNamespace = "") java.util.List<org.eclipse.servicesregistry.proxy.types.Service> service) throws org.eclipse.servicesregistry.proxy.types.PublishServicesFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySipublishServicesFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySipublishServicesFault1,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySipublishServicesFault12,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySipublishServicesFault123;

  /**
   * Java representation of web method [findServiceDefinitions].
   */
  @javax.jws.WebMethod(operationName = "findServiceDefinitions")
  @javax.xml.ws.RequestWrapper(localName = "findServiceDefinitions", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.FindServiceDefinitions")
  @javax.xml.ws.ResponseWrapper(localName = "findServiceDefinitionsResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.FindServiceDefinitionsResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public org.eclipse.servicesregistry.proxy.types.ServiceDefinitionsList findServiceDefinitions(@javax.jws.WebParam(name = "serviceDefinitionSearchAttributes", targetNamespace = "") org.eclipse.servicesregistry.proxy.types.ServiceDefinitionSearchAttributes serviceDefinitionSearchAttributes) throws org.eclipse.servicesregistry.proxy.types.FindServiceDefinitionsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySifindServiceDefinitionsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySifindServiceDefinitionsFault1,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySifindServiceDefinitionsFault12;

  /**
   * Java representation of web method [getClassificationSystemValuesFlat].
   */
  @javax.jws.WebMethod(operationName = "getClassificationSystemValuesFlat")
  @javax.xml.ws.RequestWrapper(localName = "getClassificationSystemValuesFlat", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.GetClassificationSystemValuesFlat")
  @javax.xml.ws.ResponseWrapper(localName = "getClassificationSystemValuesFlatResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.GetClassificationSystemValuesFlatResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public org.eclipse.servicesregistry.proxy.types.ClassificationSystemValueListFlat getClassificationSystemValuesFlat(@javax.jws.WebParam(name = "classificationSystemKey", targetNamespace = "") org.eclipse.servicesregistry.proxy.types.ClassificationSystemKey classificationSystemKey, @javax.jws.WebParam(name = "version", targetNamespace = "") long version, @javax.jws.WebParam(name = "listHead", targetNamespace = "") int listHead, @javax.jws.WebParam(name = "maxRows", targetNamespace = "") int maxRows) throws org.eclipse.servicesregistry.proxy.types.GetClassificationSystemValuesFlatFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySigetClassificationSystemValuesFlatFault;

  /**
   * Java representation of web method [getGroupClassificationSystems].
   */
  @javax.jws.WebMethod(operationName = "getGroupClassificationSystems")
  @javax.xml.ws.RequestWrapper(localName = "getGroupClassificationSystems", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.GetGroupClassificationSystems")
  @javax.xml.ws.ResponseWrapper(localName = "getGroupClassificationSystemsResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.GetGroupClassificationSystemsResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public java.util.List<org.eclipse.servicesregistry.proxy.types.GroupClassificationSystem> getGroupClassificationSystems(@javax.jws.WebParam(name = "classificationSystemKeys", targetNamespace = "") java.util.List<org.eclipse.servicesregistry.proxy.types.ClassificationSystemKey> classificationSystemKeys) throws org.eclipse.servicesregistry.proxy.types.GetGroupClassificationSystemsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySigetGroupClassificationSystemsFault;

  /**
   * Java representation of web method [deleteServices].
   */
  @javax.jws.WebMethod(operationName = "deleteServices")
  @javax.xml.ws.RequestWrapper(localName = "deleteServices", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.DeleteServices")
  @javax.xml.ws.ResponseWrapper(localName = "deleteServicesResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.DeleteServicesResponse")
  public void deleteServices(@javax.jws.WebParam(name = "deleteServiceIdentifires", targetNamespace = "") java.util.List<org.eclipse.servicesregistry.proxy.types.DeleteServiceIdentifier> deleteServiceIdentifires) throws org.eclipse.servicesregistry.proxy.types.DeleteServicesFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySideleteServicesFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySideleteServicesFault1,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySideleteServicesFault12;

  /**
   * Java representation of web method [findServiceEndpoints].
   */
  @javax.jws.WebMethod(operationName = "findServiceEndpoints")
  @javax.xml.ws.RequestWrapper(localName = "findServiceEndpoints", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.FindServiceEndpoints")
  @javax.xml.ws.ResponseWrapper(localName = "findServiceEndpointsResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.FindServiceEndpointsResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public org.eclipse.servicesregistry.proxy.types.ServiceEndpointList findServiceEndpoints(@javax.jws.WebParam(name = "serviceEndpointSearchAttributes", targetNamespace = "") org.eclipse.servicesregistry.proxy.types.ServiceEndpointSearchAttributes serviceEndpointSearchAttributes) throws org.eclipse.servicesregistry.proxy.types.FindServiceEndpointsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySifindServiceEndpointsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySifindServiceEndpointsFault1,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySifindServiceEndpointsFault12;

  /**
   * Java representation of web method [getGroupClassificationSystemValuesFlat].
   */
  @javax.jws.WebMethod(operationName = "getGroupClassificationSystemValuesFlat")
  @javax.xml.ws.RequestWrapper(localName = "getGroupClassificationSystemValuesFlat", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.GetGroupClassificationSystemValuesFlat")
  @javax.xml.ws.ResponseWrapper(localName = "getGroupClassificationSystemValuesFlatResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.GetGroupClassificationSystemValuesFlatResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public org.eclipse.servicesregistry.proxy.types.ClassificationGroupColumnList getGroupClassificationSystemValuesFlat(@javax.jws.WebParam(name = "classificationSystemKey", targetNamespace = "") org.eclipse.servicesregistry.proxy.types.ClassificationSystemKey classificationSystemKey, @javax.jws.WebParam(name = "version", targetNamespace = "") long version, @javax.jws.WebParam(name = "listHead", targetNamespace = "") int listHead, @javax.jws.WebParam(name = "maxRows", targetNamespace = "") int maxRows) throws org.eclipse.servicesregistry.proxy.types.GetGroupClassificationSystemValuesFlatFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySigetGroupClassificationSystemValuesFlatFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySigetGroupClassificationSystemValuesFlatFault1,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySigetGroupClassificationSystemValuesFlatFault12;

  /**
   * Java representation of web method [notifyPhysicalSystem].
   */
  @javax.jws.WebMethod(operationName = "notifyPhysicalSystem")
  @javax.xml.ws.RequestWrapper(localName = "notifyPhysicalSystem", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.NotifyPhysicalSystem")
  @javax.xml.ws.ResponseWrapper(localName = "notifyPhysicalSystemResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.NotifyPhysicalSystemResponse")
  public void notifyPhysicalSystem(@javax.jws.WebParam(name = "details", targetNamespace = "") java.util.List<org.eclipse.servicesregistry.proxy.types.NotificationDetails> details, @javax.jws.WebParam(name = "notificationQname", targetNamespace = "") javax.xml.namespace.QName notificationQname, @javax.jws.WebParam(name = "physicalSystemKey", targetNamespace = "") org.eclipse.servicesregistry.proxy.types.PhysicalSystemKey physicalSystemKey) throws org.eclipse.servicesregistry.proxy.types.NotifyPhysicalSystemFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySinotifyPhysicalSystemFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySinotifyPhysicalSystemFault1,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySinotifyPhysicalSystemFault12;

  /**
   * Java representation of web method [findServiceDefinitionsByKeywords].
   */
  @javax.jws.WebMethod(operationName = "findServiceDefinitionsByKeywords")
  @javax.xml.ws.RequestWrapper(localName = "findServiceDefinitionsByKeywords", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.FindServiceDefinitionsByKeywords")
  @javax.xml.ws.ResponseWrapper(localName = "findServiceDefinitionsByKeywordsResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.FindServiceDefinitionsByKeywordsResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public org.eclipse.servicesregistry.proxy.types.ServiceDefinitionsList findServiceDefinitionsByKeywords(@javax.jws.WebParam(name = "expression", targetNamespace = "") java.lang.String expression) throws org.eclipse.servicesregistry.proxy.types.FindServiceDefinitionsByKeywordsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySifindServiceDefinitionsByKeywordsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySifindServiceDefinitionsByKeywordsFault1,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySifindServiceDefinitionsByKeywordsFault12;

  /**
   * Java representation of web method [getClassificationSystemsGreaterThanVersion].
   */
  @javax.jws.WebMethod(operationName = "getClassificationSystemsGreaterThanVersion")
  @javax.xml.ws.RequestWrapper(localName = "getClassificationSystemsGreaterThanVersion", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.GetClassificationSystemsGreaterThanVersion")
  @javax.xml.ws.ResponseWrapper(localName = "getClassificationSystemsGreaterThanVersionResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.GetClassificationSystemsGreaterThanVersionResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public org.eclipse.servicesregistry.proxy.types.ClassificationSystemList getClassificationSystemsGreaterThanVersion(@javax.jws.WebParam(name = "version", targetNamespace = "") long version, @javax.jws.WebParam(name = "listHead", targetNamespace = "") int listHead, @javax.jws.WebParam(name = "maxRows", targetNamespace = "") int maxRows) throws org.eclipse.servicesregistry.proxy.types.GetClassificationSystemsGreaterThanVersionFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySigetClassificationSystemsGreaterThanVersionFault;

  /**
   * Java representation of web method [publishClassificationSystems].
   */
  @javax.jws.WebMethod(operationName = "publishClassificationSystems")
  @javax.xml.ws.RequestWrapper(localName = "publishClassificationSystems", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.PublishClassificationSystems")
  @javax.xml.ws.ResponseWrapper(localName = "publishClassificationSystemsResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.PublishClassificationSystemsResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public java.util.List<org.eclipse.servicesregistry.proxy.types.ClassificationSystemKey> publishClassificationSystems(@javax.jws.WebParam(name = "classificationSystems", targetNamespace = "") java.util.List<org.eclipse.servicesregistry.proxy.types.ClassificationSystem> classificationSystems) throws org.eclipse.servicesregistry.proxy.types.PublishClassificationSystemsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySipublishClassificationSystemsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySipublishClassificationSystemsFault1,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySipublishClassificationSystemsFault12,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySipublishClassificationSystemsFault123;

  /**
   * Java representation of web method [publishClassificationSystemValuesFlat].
   */
  @javax.jws.WebMethod(operationName = "publishClassificationSystemValuesFlat")
  @javax.xml.ws.RequestWrapper(localName = "publishClassificationSystemValuesFlat", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.PublishClassificationSystemValuesFlat")
  @javax.xml.ws.ResponseWrapper(localName = "publishClassificationSystemValuesFlatResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.PublishClassificationSystemValuesFlatResponse")
  public void publishClassificationSystemValuesFlat(@javax.jws.WebParam(name = "classificationSystemKey", targetNamespace = "") org.eclipse.servicesregistry.proxy.types.ClassificationSystemKey classificationSystemKey, @javax.jws.WebParam(name = "values", targetNamespace = "") java.util.List<org.eclipse.servicesregistry.proxy.types.ClassificationSystemValueFlat> values) throws org.eclipse.servicesregistry.proxy.types.PublishClassificationSystemValuesFlatFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySipublishClassificationSystemValuesFlatFault;

  /**
   * Java representation of web method [publishGroupClassificationSystemValuesFlat].
   */
  @javax.jws.WebMethod(operationName = "publishGroupClassificationSystemValuesFlat")
  @javax.xml.ws.RequestWrapper(localName = "publishGroupClassificationSystemValuesFlat", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.PublishGroupClassificationSystemValuesFlat")
  @javax.xml.ws.ResponseWrapper(localName = "publishGroupClassificationSystemValuesFlatResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.PublishGroupClassificationSystemValuesFlatResponse")
  public void publishGroupClassificationSystemValuesFlat(@javax.jws.WebParam(name = "classificationSystemKey", targetNamespace = "") org.eclipse.servicesregistry.proxy.types.ClassificationSystemKey classificationSystemKey, @javax.jws.WebParam(name = "values", targetNamespace = "") java.util.List<org.eclipse.servicesregistry.proxy.types.ClassificationGroupValue> values) throws org.eclipse.servicesregistry.proxy.types.PublishGroupClassificationSystemValuesFlatFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySipublishGroupClassificationSystemValuesFlatFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySipublishGroupClassificationSystemValuesFlatFault1,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySipublishGroupClassificationSystemValuesFlatFault12;

  /**
   * Java representation of web method [findClassificationSystemsPerPhysicalSystems].
   */
  @javax.jws.WebMethod(operationName = "findClassificationSystemsPerPhysicalSystems")
  @javax.xml.ws.RequestWrapper(localName = "findClassificationSystemsPerPhysicalSystems", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.FindClassificationSystemsPerPhysicalSystems")
  @javax.xml.ws.ResponseWrapper(localName = "findClassificationSystemsPerPhysicalSystemsResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.FindClassificationSystemsPerPhysicalSystemsResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public org.eclipse.servicesregistry.proxy.types.ClassificationSystemList findClassificationSystemsPerPhysicalSystems(@javax.jws.WebParam(name = "physicalSystemKeys", targetNamespace = "") java.util.List<org.eclipse.servicesregistry.proxy.types.PhysicalSystemKey> physicalSystemKeys, @javax.jws.WebParam(name = "listHead", targetNamespace = "") int listHead, @javax.jws.WebParam(name = "maxRows", targetNamespace = "") int maxRows) throws org.eclipse.servicesregistry.proxy.types.FindClassificationSystemsPerPhysicalSystemsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySifindClassificationSystemsPerPhysicalSystemsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySifindClassificationSystemsPerPhysicalSystemsFault1,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySifindClassificationSystemsPerPhysicalSystemsFault12;

  /**
   * Java representation of web method [findGroupClassificationValuesPerPhysicalSystems].
   */
  @javax.jws.WebMethod(operationName = "findGroupClassificationValuesPerPhysicalSystems")
  @javax.xml.ws.RequestWrapper(localName = "findGroupClassificationValuesPerPhysicalSystems", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.FindGroupClassificationValuesPerPhysicalSystems")
  @javax.xml.ws.ResponseWrapper(localName = "findGroupClassificationValuesPerPhysicalSystemsResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.FindGroupClassificationValuesPerPhysicalSystemsResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public org.eclipse.servicesregistry.proxy.types.ClassificationGroupNodeList findGroupClassificationValuesPerPhysicalSystems(@javax.jws.WebParam(name = "classificationSystemKey", targetNamespace = "") org.eclipse.servicesregistry.proxy.types.ClassificationSystemKey classificationSystemKey, @javax.jws.WebParam(name = "physicalSystemKey", targetNamespace = "") java.util.List<org.eclipse.servicesregistry.proxy.types.PhysicalSystemKey> physicalSystemKey, @javax.jws.WebParam(name = "listHead", targetNamespace = "") int listHead, @javax.jws.WebParam(name = "maxRows", targetNamespace = "") int maxRows) throws org.eclipse.servicesregistry.proxy.types.FindGroupClassificationValuesPerPhysicalSystemsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySifindGroupClassificationValuesPerPhysicalSystemsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySifindGroupClassificationValuesPerPhysicalSystemsFault1,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySifindGroupClassificationValuesPerPhysicalSystemsFault12;

  /**
   * Java representation of web method [findPhysicalSystemsPerGroupClassifcationValues].
   */
  @javax.jws.WebMethod(operationName = "findPhysicalSystemsPerGroupClassifcationValues")
  @javax.xml.ws.RequestWrapper(localName = "findPhysicalSystemsPerGroupClassifcationValues", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.FindPhysicalSystemsPerGroupClassifcationValues")
  @javax.xml.ws.ResponseWrapper(localName = "findPhysicalSystemsPerGroupClassifcationValuesResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.FindPhysicalSystemsPerGroupClassifcationValuesResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public org.eclipse.servicesregistry.proxy.types.PhysicalSystemList findPhysicalSystemsPerGroupClassifcationValues(@javax.jws.WebParam(name = "values", targetNamespace = "") java.util.List<org.eclipse.servicesregistry.proxy.types.ClassificationGroupNode> values, @javax.jws.WebParam(name = "listHead", targetNamespace = "") int listHead, @javax.jws.WebParam(name = "maxRows", targetNamespace = "") int maxRows) throws org.eclipse.servicesregistry.proxy.types.FindPhysicalSystemsPerGroupClassifcationValuesFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySifindPhysicalSystemsPerGroupClassifcationValuesFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySifindPhysicalSystemsPerGroupClassifcationValuesFault1,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySifindPhysicalSystemsPerGroupClassifcationValuesFault12;

  /**
   * Java representation of web method [getClassificationSystemValues].
   */
  @javax.jws.WebMethod(operationName = "getClassificationSystemValues")
  @javax.xml.ws.RequestWrapper(localName = "getClassificationSystemValues", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.GetClassificationSystemValues")
  @javax.xml.ws.ResponseWrapper(localName = "getClassificationSystemValuesResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.GetClassificationSystemValuesResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public org.eclipse.servicesregistry.proxy.types.ClassificationSystemValueList getClassificationSystemValues(@javax.jws.WebParam(name = "classificationSystemKey", targetNamespace = "") org.eclipse.servicesregistry.proxy.types.ClassificationSystemKey classificationSystemKey, @javax.jws.WebParam(name = "version", targetNamespace = "") long version, @javax.jws.WebParam(name = "listHead", targetNamespace = "") int listHead, @javax.jws.WebParam(name = "maxRows", targetNamespace = "") int maxRows) throws org.eclipse.servicesregistry.proxy.types.GetClassificationSystemValuesFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySigetClassificationSystemValuesFault;

  /**
   * Java representation of web method [getGroupClassificationSystemValues].
   */
  @javax.jws.WebMethod(operationName = "getGroupClassificationSystemValues")
  @javax.xml.ws.RequestWrapper(localName = "getGroupClassificationSystemValues", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.GetGroupClassificationSystemValues")
  @javax.xml.ws.ResponseWrapper(localName = "getGroupClassificationSystemValuesResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.GetGroupClassificationSystemValuesResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public org.eclipse.servicesregistry.proxy.types.ClassificationGroupNodeList getGroupClassificationSystemValues(@javax.jws.WebParam(name = "classificationSystemKey", targetNamespace = "") org.eclipse.servicesregistry.proxy.types.ClassificationSystemKey classificationSystemKey, @javax.jws.WebParam(name = "version", targetNamespace = "") long version, @javax.jws.WebParam(name = "listHead", targetNamespace = "") int listHead, @javax.jws.WebParam(name = "maxRows", targetNamespace = "") int maxRows) throws org.eclipse.servicesregistry.proxy.types.GetGroupClassificationSystemValuesFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySigetGroupClassificationSystemValuesFault;

  /**
   * Java representation of web method [publishClassificationSystemValues].
   */
  @javax.jws.WebMethod(operationName = "publishClassificationSystemValues")
  @javax.xml.ws.RequestWrapper(localName = "publishClassificationSystemValues", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.PublishClassificationSystemValues")
  @javax.xml.ws.ResponseWrapper(localName = "publishClassificationSystemValuesResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.PublishClassificationSystemValuesResponse")
  public void publishClassificationSystemValues(@javax.jws.WebParam(name = "classificationSystemKey", targetNamespace = "") org.eclipse.servicesregistry.proxy.types.ClassificationSystemKey classificationSystemKey, @javax.jws.WebParam(name = "values", targetNamespace = "") java.util.List<org.eclipse.servicesregistry.proxy.types.ClassificationSystemValue> values) throws org.eclipse.servicesregistry.proxy.types.PublishClassificationSystemValuesFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySipublishClassificationSystemValuesFault;

  /**
   * Java representation of web method [publishGroupClassificationSystemValues].
   */
  @javax.jws.WebMethod(operationName = "publishGroupClassificationSystemValues")
  @javax.xml.ws.RequestWrapper(localName = "publishGroupClassificationSystemValues", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.PublishGroupClassificationSystemValues")
  @javax.xml.ws.ResponseWrapper(localName = "publishGroupClassificationSystemValuesResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.PublishGroupClassificationSystemValuesResponse")
  public void publishGroupClassificationSystemValues(@javax.jws.WebParam(name = "classificationSystemKey", targetNamespace = "") org.eclipse.servicesregistry.proxy.types.ClassificationSystemKey classificationSystemKey, @javax.jws.WebParam(name = "values", targetNamespace = "") java.util.List<org.eclipse.servicesregistry.proxy.types.ClassificationGroupNode> values) throws org.eclipse.servicesregistry.proxy.types.PublishGroupClassificationSystemValuesFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySipublishGroupClassificationSystemValuesFault;

  /**
   * Java representation of web method [findClassificationValuesPerPhysicalSystems].
   */
  @javax.jws.WebMethod(operationName = "findClassificationValuesPerPhysicalSystems")
  @javax.xml.ws.RequestWrapper(localName = "findClassificationValuesPerPhysicalSystems", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.FindClassificationValuesPerPhysicalSystems")
  @javax.xml.ws.ResponseWrapper(localName = "findClassificationValuesPerPhysicalSystemsResponse", targetNamespace = "http://sap.com/esi/uddi/sr/api/ws/", className = "org.eclipse.servicesregistry.proxy.types.FindClassificationValuesPerPhysicalSystemsResponse")
  @javax.jws.WebResult(name = "return", targetNamespace = "")
  public org.eclipse.servicesregistry.proxy.types.ClassificationSystemValueList findClassificationValuesPerPhysicalSystems(@javax.jws.WebParam(name = "classificationSystemKey", targetNamespace = "") org.eclipse.servicesregistry.proxy.types.ClassificationSystemKey classificationSystemKey, @javax.jws.WebParam(name = "physicalSystemKeys", targetNamespace = "") java.util.List<org.eclipse.servicesregistry.proxy.types.PhysicalSystemKey> physicalSystemKeys, @javax.jws.WebParam(name = "listHead", targetNamespace = "") int listHead, @javax.jws.WebParam(name = "maxRows", targetNamespace = "") int maxRows) throws org.eclipse.servicesregistry.proxy.types.FindClassificationValuesPerPhysicalSystemsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySifindClassificationValuesPerPhysicalSystemsFault,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySifindClassificationValuesPerPhysicalSystemsFault1,org.eclipse.servicesregistry.proxy.types.ServicesRegistrySifindClassificationValuesPerPhysicalSystemsFault12;

}
